### ISSUE TITLE
Invalid numbers are recognized

### ISSUE THREAD

**Issue by intrueder** [okudr/KottansTasks#1]
Pass "50000000000006114" to `GetCreditCardVendor` method
Expected result: "Unknown" (invalid number)
Actual result: "Maestro"

**Comment by okudr** [comment]
I am not sure about length(number of digits) in this example because Wiki said that Maestro may have 12-19 digits...

**Comment by intrueder** [comment]
That's why I wrote a hint in parenthesis and a title, **number is invalid** , check it with your `IsCreditCardNumberValid`, and reopen this issue.

**Comment by okudr** [comment]
Ok, I fixed it.
